#!/bin/sh

echo "Going to install Nvidia video drivers (say yes if asked to replace drivers)"

BRANCH= # Enter a branch if needed, i.e. -340xx or -304xx
NVIDIA=nvidia${BRANCH} # If no branch entered above this would be "nvidia"xrandr --listproviders

pacman -S --needed $NVIDIA ${NVIDIA}-libgl lib32-${NVIDIA}-libgl opencl-${NVIDIA} lib32-opencl-${NVIDIA}

# Get script directory;
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo -e "\nCreating symlink\nln -sf ${DIR}/xorg.conf /etc/X11/xorg.conf"
ln -sf ${DIR}/xorg.conf /etc/X11/xorg.conf

echo -e "\n### Done ###\t\t\tChanges will take effect after reboot"
